var json_BOLIVAR_CAPITALMunicipio_Bolivar_Parroquia_Capital_BolivarCapital_Bolivar_Centros_Poblados_16 = {
"type": "FeatureCollection",
"name": "BOLIVAR_CAPITALMunicipio_Bolivar_Parroquia_Capital_BolivarCapital_Bolivar_Centros_Poblados_16",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "La Isla", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.44607288283882, 7.8383414703253 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "SAN ANTONIO DEL TÁCHIRA", "descripció": "Capital Municipio", "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.446706163226366, 7.813432723181206 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Peracal", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.433870112979889, 7.791339564527082 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Las Adjuntas", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.420131628291756, 7.771960884510634 ] ] } },
{ "type": "Feature", "properties": { "pk": "5", "id": "5", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Llano de Jorge", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.467673845810737, 7.787913826945115 ] ] } },
{ "type": "Feature", "properties": { "pk": "6", "id": "6", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Sabana Potrera", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.465771207826734, 7.781374850691959 ] ] } },
{ "type": "Feature", "properties": { "pk": "7", "id": "7", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "El Saladito", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.450132974970956, 7.786517463475214 ] ] } },
{ "type": "Feature", "properties": { "pk": "8", "id": "8", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Las Tablas", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.413297077595431, 7.741463534940861 ] ] } }
]
}
