var json_BOLIVAR_CAPITALMunicipio_Bolivar_Parroquia_Capital_BolivarCapital_Bolivar_Oronimia_7 = {
"type": "FeatureCollection",
"name": "BOLIVAR_CAPITALMunicipio_Bolivar_Parroquia_Capital_BolivarCapital_Bolivar_Oronimia_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Cerro Capote", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.403475550766245, 7.74079134152875 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Cerro Rangel", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.440337857591402, 7.776918252228838 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Cerro la Guacara", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.441485393852489, 7.753684457289865 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "200401", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "4", "municipio": "Bolívar", "capital_mu": "San Antonio del Táchira", "código_par": "1", "parroquia": "Capital Bolívar", "capital_pa": "San Antonio del Táchira", "nombre": "Cerro de Pajarita", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.399805463407404, 7.748625993487073 ] ] } }
]
}
